### ISSUE TITLE
[请求] 更新 electron 依赖版本到 16.2.2

### ISSUE THREAD

**Issue by arenekosreal** [daihy8759/ieaseMusic#11]
16.2.2 是 electron16 的最后一个稳定版，Arch Linux 的 electron16 软件包中的 electron 也是这个版本。程序的 electron 依赖版本更新至这个版本之后可以实现将程序的资源单独提取出来，让所有的 electron 应用共享系统的 electron，从而节省程序 electron 部分的大量空间占用。目前的 16.0.2 的 electron 作为依赖后构建出的资源文件 `app.asar` 无法使用 16.2.2 的 electron 加载。

**Comment by daihy8759** [comment]
升级到18.2.0了
