### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by Mackel123** [daihy8759/ieaseMusic#2]
请问如何打包呢？能否多加一点说明呢？

**Comment by TanghaohanSC** [comment]
+1

**Comment by daihy8759** [comment]
你们是遇到啥问题了呢，yarn install && yarn build就能打包了

**Comment by Mackel123** [comment]
主要是opensuse貌似没有yarn这个包~如果是这样的话，我再尝试一下吧~不好意思很久没有看到，因为我现在换windows了，主要在学after effects

**Comment by Mackel123** [comment]
作者有没有捐赠渠道，我这边捐赠个几块钱吧

**Comment by daihy8759** [comment]
您的心意在下领了，捐赠就不用啦。yarn是node下的包管理工具，可以等同与npm(速度快一点)，因为用习惯了很少用npm。可以通过npm install -g yarn安装使用，也可以直接用npm run代替yarn，前提就是本地必须有node环境。
