### ISSUE TITLE
无法播放歌曲

### ISSUE THREAD

**Issue by ayamir** [daihy8759/ieaseMusic#9]
一直处于加载的状态，`Network`窗口只能看到jpg能全部加载出来，主窗口一直是UNKNOW KBPS
![image](https://user-images.githubusercontent.com/61657399/159836300-1542484a-9d95-4dd6-a012-55775a4f0c5a.png)

**Comment by daihy8759** [comment]
具体是从那个界面播放不了呢

**Comment by ayamir** [comment]
歌是从我喜欢里面播的

**Comment by ayamir** [comment]
事实上不管是从哪里播的歌都没法正常播放

**Comment by ayamir** [comment]
很奇怪，刚刚使用又好了，还有个小问题：`src/renderer/`目录下的`app.less`应该改名为`App.less`否则会报错。

**Comment by daihy8759** [comment]
Mac下没问题，可能其他系统区分大小写，我改一下。。
